language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py35-django19-drf33
    - TOX_ENV=py35-django18-drf33
    - TOX_ENV=py35-django18-drf32
    - TOX_ENV=py35-django18-drf31
    - TOX_ENV=py35-django18-drf30
    - TOX_ENV=py34-django19-drf33
    - TOX_ENV=py34-django18-drf33
    - TOX_ENV=py34-django18-drf32
    - TOX_ENV=py34-django18-drf31
    - TOX_ENV=py34-django18-drf30
    - TOX_ENV=py34-django17-drf33
    - TOX_ENV=py34-django17-drf32
    - TOX_ENV=py34-django17-drf31
    - TOX_ENV=py34-django17-drf30
    - TOX_ENV=py34-django17-drf24
    - TOX_ENV=py33-django18-drf33
    - TOX_ENV=py33-django18-drf32
    - TOX_ENV=py33-django18-drf31
    - TOX_ENV=py33-django18-drf30
    - TOX_ENV=py33-django17-drf33
    - TOX_ENV=py33-django17-drf32
    - TOX_ENV=py33-django17-drf31
    - TOX_ENV=py33-django17-drf30
    - TOX_ENV=py33-django17-drf24
    - TOX_ENV=py33-django16-drf32
    - TOX_ENV=py33-django16-drf31
    - TOX_ENV=py33-django16-drf30
    - TOX_ENV=py33-django16-drf24
    - TOX_ENV=py27-django19-drf33
    - TOX_ENV=py27-django18-drf33
    - TOX_ENV=py27-django18-drf32
    - TOX_ENV=py27-django18-drf31
    - TOX_ENV=py27-django18-drf30
    - TOX_ENV=py27-django17-drf33
    - TOX_ENV=py27-django17-drf32
    - TOX_ENV=py27-django17-drf31
    - TOX_ENV=py27-django17-drf30
    - TOX_ENV=py27-django17-drf24
    - TOX_ENV=py27-django16-drf32
    - TOX_ENV=py27-django16-drf31
    - TOX_ENV=py27-django16-drf30
    - TOX_ENV=py27-django16-drf24

matrix:
  fast_finish: true

addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - python3.5

install:
    - pip install tox
    - pip install -r requirements.txt
    - pip install pytest-django
    - pip install flake8
    - pip install coveralls

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

deploy:
  provider: pypi
  user: RaphaelGyory
  password:
    secure: ii+5Nxxs7CAlt/UuGJSsADxcJAuhStdpcWlB303wuWjrwuSOrY8CiuIwPkRxi/cG/MJdAuELvDeAXGAFSboeUjnYwpdYgIfkd9KObPu40pGaWlSSAP5zO+qlJ+P1BLXr3Te+Q54o7NtHyDXv8DbDbvbb82HQIxzD0HMTQ4lzanfPDDy3lsJlB65NnYudcAzXKjLUfLB2e59ngNKmgW0pzUTFTuSKhJ4RPdMWTkfTzVXwclryUbp4iWOMrb/fgr+yxbr+p93N/Vv74NbN9amcaFrQ9C9/Qz0iIoF7yAYvK2xHnAO9dtZrYUGlfxIGgWoIBd5hvM3Z5bGBNsMfFZVDgvTgIR1nJ6PKkwSdW+U/KZl4HSGzRGICP3YVjzUAhEjewpR18AQTI6ijojW2nAWvJFEyAf2nHbNytLqzfl1IXfTvEH0SLs81fm0aKEP77ZY1d+2m58pcMz94ZEolSZwzO3H18YjRkOrNhu2pofQXCmIP0geBduCNJVzwmNRxudUW2v2J0vzDcfwYoU5WcwKqxOMz6DnSQhYEuHTblfPRf2KqdxsXoHnwerS+x8bgnNwanIuOF/qHxEUvvKPxi8Qs+OgqUXhJl4eXQ+biKjvMOu4KMwDEcQQUN5GYcaS1udgM64jdi6J66eX1MBCb6Dw81YQIgXNBvLyoWw4UHEUscss=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: raphaelgyory/django-rest-messaging
