language: python

sudo: false

env:
    - TOX_ENV=py27-lint
    - TOX_ENV=py27-docs
    - TOX_ENV=py35-django19-drf33
    - TOX_ENV=py35-django18-drf33
    - TOX_ENV=py35-django18-drf32
    - TOX_ENV=py35-django18-drf31
    - TOX_ENV=py35-django18-drf30
    - TOX_ENV=py34-django19-drf33
    - TOX_ENV=py34-django18-drf33
    - TOX_ENV=py34-django18-drf32
    - TOX_ENV=py34-django18-drf31
    - TOX_ENV=py34-django18-drf30
    - TOX_ENV=py34-django17-drf33
    - TOX_ENV=py34-django17-drf32
    - TOX_ENV=py34-django17-drf31
    - TOX_ENV=py34-django17-drf30
    - TOX_ENV=py34-django17-drf24
    - TOX_ENV=py33-django18-drf33
    - TOX_ENV=py33-django18-drf32
    - TOX_ENV=py33-django18-drf31
    - TOX_ENV=py33-django18-drf30
    - TOX_ENV=py33-django17-drf33
    - TOX_ENV=py33-django17-drf32
    - TOX_ENV=py33-django17-drf31
    - TOX_ENV=py33-django17-drf30
    - TOX_ENV=py33-django17-drf24
    - TOX_ENV=py33-django16-drf32
    - TOX_ENV=py33-django16-drf31
    - TOX_ENV=py33-django16-drf30
    - TOX_ENV=py33-django16-drf24
    - TOX_ENV=py27-django19-drf33
    - TOX_ENV=py27-django18-drf33
    - TOX_ENV=py27-django18-drf32
    - TOX_ENV=py27-django18-drf31
    - TOX_ENV=py27-django18-drf30
    - TOX_ENV=py27-django17-drf33
    - TOX_ENV=py27-django17-drf32
    - TOX_ENV=py27-django17-drf31
    - TOX_ENV=py27-django17-drf30
    - TOX_ENV=py27-django17-drf24
    - TOX_ENV=py27-django16-drf32
    - TOX_ENV=py27-django16-drf31
    - TOX_ENV=py27-django16-drf30
    - TOX_ENV=py27-django16-drf24

matrix:
  fast_finish: true

install:
  # Virtualenv < 14 is required to keep the Python 3.2 builds running.
  - pip install tox "virtualenv<14"

script:
    - tox -e $TOX_ENV

