site_name: Django Rest Messaging
site_description: The project provides a Facebook-like messaging API for django rest framework.
repo_url: https://github.com/raphaelgyory/django-rest-messaging
site_dir: site
theme: bootstrap
pages:
- The project: index.md
- REST: django-rest-messaging.md
- Real-time: django-rest-messaging-centrifugo.md
- React.js: django-rest-messaging-js.md
copyright: <p class="text-muted">Xelles SPRL. 57 avenue Everard, 1190 Brussels, Belgium. VAT BE 0546.833.144. IBAN BE62 7320 3209 8361. BIC CREGBEBB.</p>